// Every mission leaves a git snapshot of the organisation folder: one commit before it starts (so the
// owner's own edits are kept) and one when it ends. "Undo" reverts a mission's commits in a new commit,
// so nothing is ever lost and the full history stays readable with any git tool.
import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';

const IGNORE = ['# Generated by Jarvis: build products and secrets are not part of the history', 'node_modules/', '.venv/', 'venv/', '__pycache__/', 'dist/', 'build/', '.next/', '.playwright/', '*.log', '.env', '.env.*', 'knowledge/', ''].join('\n');

function git(root, args, { allowFail = false } = {}) {
  const r = spawnSync('git', args, { cwd: root, encoding: 'utf8', windowsHide: true, env: { ...process.env, GIT_TERMINAL_PROMPT: '0', GIT_OPTIONAL_LOCKS: '0' } });
  if (r.error) throw r.error;
  if (r.status !== 0 && !allowFail) throw new Error((r.stderr || r.stdout || `git ${args[0]} failed`).trim().slice(0, 300));
  return r;
}

let available = null;
export function gitAvailable() {
  if (available === null) {
    try {
      available = spawnSync('git', ['--version'], { encoding: 'utf8', windowsHide: true }).status === 0;
    } catch {
      available = false;
    }
  }
  return available;
}

export function ensureRepo(root) {
  if (!gitAvailable()) return false;
  const fresh = !fs.existsSync(path.join(root, '.git'));
  if (fresh) {
    git(root, ['init', '-q']);
    git(root, ['config', 'user.name', 'Jarvis']);
    git(root, ['config', 'user.email', 'jarvis@localhost']);
    git(root, ['config', 'core.autocrlf', 'false']);
    git(root, ['config', 'core.safecrlf', 'false']);
  }
  const ignore = path.join(root, '.gitignore');
  if (!fs.existsSync(ignore)) fs.writeFileSync(ignore, IGNORE);
  if (fresh) {
    git(root, ['add', '-A']);
    git(root, ['commit', '-q', '--allow-empty', '-m', 'Initial snapshot (before Jarvis started keeping history)']);
  }
  return true;
}

// Commits everything that changed; returns the commit id, or null when nothing changed (or git is missing).
export function snapshot(root, message) {
  try {
    if (!ensureRepo(root)) return null;
    git(root, ['add', '-A']);
    if (git(root, ['diff', '--cached', '--quiet'], { allowFail: true }).status === 0) return null;
    git(root, ['commit', '-q', '-m', message]);
    return git(root, ['rev-parse', 'HEAD']).stdout.trim();
  } catch (err) {
    return null; // history is a convenience; it never blocks a mission
  }
}

// Reverts the given commits (newest first) in one new commit. Returns the undo commit id, or null when there was nothing to revert.
export function undo(root, shas, message) {
  if (!ensureRepo(root)) throw new Error('git is not installed on this computer');
  snapshot(root, 'Before undo'); // keep any work in progress
  try {
    for (const sha of [...shas].reverse()) git(root, ['revert', '--no-commit', '--no-edit', sha]);
  } catch (err) {
    git(root, ['revert', '--abort'], { allowFail: true });
    git(root, ['reset', '--hard', 'HEAD'], { allowFail: true });
    throw new Error(`Could not undo cleanly: ${err.message}`);
  }
  if (git(root, ['diff', '--cached', '--quiet'], { allowFail: true }).status === 0) return null;
  git(root, ['commit', '-q', '-m', message]);
  return git(root, ['rev-parse', 'HEAD']).stdout.trim();
}

// Files touched by a commit.
export function filesIn(root, sha) {
  try {
    return git(root, ['show', '--name-only', '--pretty=format:', sha]).stdout.split(/\r?\n/).filter(Boolean);
  } catch {
    return [];
  }
}
